# 서버 설정
server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8

# 뷰리졸버 설정
spring:
  mvc:
    view:
      prefix: /WEB-INF/thecar/
      suffix: .jsp
  # 데이터소스 설정
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/test
    username: ${DB_ID}
    password: ${DB_PASSWORD}

kakaomap_key: ${JAVASCRIPT_KEY}