# 서버 설정
server:
  port: 5000
  #port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      
# 뷰리졸버 설정
spring:
  mvc:
    view:
      prefix: /WEB-INF/thecar/
      suffix: .jsp
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/test
    #url: jdbc:h2:mem:thecar
    username: sa
    password:
  jpa:
    open-in-view: true
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        "[format_sql]": true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 329544797681-o46c2acbp189c2gs70hhl60m6r985frm.apps.googleusercontent.com
            client-secret: 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
            scope: email, profile
    
# 카카오 ID, 비밀번호
kakao:
  default:
    id: ee0b7525aab13922c886f01538c0d6f6
    password: kakaoabc123!

# 구글 비밀번호
google:
  default:
    password: googleabc123!